name: drag_and_drop_chatting_app
description: A Flutter app with draggable/resizable text and image chat boxes.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  emoji_picker_flutter: ^3.1.0
  bcrypt: ^1.1.3
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  image_picker: ^1.1.2
  image: ^4.2.0
  flutter_colorpicker: ^1.0.3
  google_fonts: ^6.2.1
  http: ^1.2.2
  firebase_messaging: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/Logo.png"   # <-- BURAYA TAŞI
  min_sdk_android: 21

flutter_native_splash:
  background_image: assets/splash/gradient_bg.png
  image: assets/icon/Logo.png          # <-- BURAYA TAŞI
  android: true
  ios: false

flutter:
  uses-material-design: true
  assets:
    - assets/icon/Logo.png
    - assets/splash/gradient_bg.png   # ✅ bunu da ekle
    - assets/splash/seamless_bg.png   # ✅ chat ekranı için
